import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Link from "next/link";

const socialUrls = {
  linkedin: "https://linkedin.com/in/euanhouse",
  github: "https://github.com/ehouse3",
};

const projectPaths = {
  covidDashboard: "/projects/covid-dashboard",
  nittanyBusiness: "/projects/nittany-business",
  tableTopSimulator: "/projects/tabletop-simulator",
  taskManager: "/projects//task-manager",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar(): ReactNode {
  return (
    <div className="flex gap-4">
      <div id="home">
        <Link href="/">Euan House</Link>
      </div>
      <div id="projects">
        <Link href={projectPaths.taskManager}>Task Manager</Link>
        <Link href={projectPaths.covidDashboard}>Covid Dashboard</Link>
        <Link href={projectPaths.nittanyBusiness}>
          Nittany Business Applcation
        </Link>
        <Link href={projectPaths.tableTopSimulator}>Tabletop Simulator</Link>
      </div>
      <div id="socials">
        <Link href={socialUrls.linkedin}>{/* <Image></Image> */}Linkedin</Link>
        <Link href={socialUrls.github}>{/* <Image></Image> */}Github</Link>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
