import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Link from "next/link";
import { HeaderLink } from "@/components/components";

const socialUrls = {
  linkedin: "https://linkedin.com/in/euanhouse",
  github: "https://github.com/ehouse3",
};

const projectPaths = {
  covidDashboard: "/projects/covid-dashboard",
  nittanyBusiness: "/projects/nittany-business",
  tableTopSimulator: "/projects/tabletop-simulator",
  taskManager: "/projects//task-manager",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar(): ReactNode {
  return (
    <div className="grid grid-cols-[1fr_2fr_1fr] items-start">
      <div id="home" className="border border-red-500">
        <Link href="/">
          <div className="text-5xl">Euan House</div>
        </Link>
      </div>
      <div id="projects" className="flex justify-around border border-red-500">
        <HeaderLink href={projectPaths.taskManager}>
          <h1>Task Manager</h1>
        </HeaderLink>
        <HeaderLink href={projectPaths.covidDashboard}>
          <h1>Covid Dashboard</h1>
        </HeaderLink>
        <HeaderLink href={projectPaths.nittanyBusiness}>
          <h1>Nittany Business Applcation</h1>
        </HeaderLink>
        <HeaderLink href={projectPaths.tableTopSimulator}>
          <h1>Tabletop Simulator</h1>
        </HeaderLink>
      </div>
      <div
        id="socials"
        className="flex justify-end gap-4 px-4 border border-red-500"
      >
        <Link href={socialUrls.linkedin}>
          {<i className="ci ci-linkedin ci-3x"></i>}
        </Link>
        <Link href={socialUrls.github}>
          {<i className="ci ci-github-light ci-3x"></i>}
        </Link>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* CDN for social media icons, consider self hosting? */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/dheereshag/coloured-icons@1.9.7/app/ci.min.css"
        />
      </head>
      <body className="min-h-full">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
